<?php

namespace App;

use App\Notifications\ThreadWasUpdated;
use App\Traits\RecordsActivity;
use Illuminate\Database\Eloquent\Model;
use ReflectionClass;

/**
 * App\Thread
 *
 * @mixin \Eloquent
 * @property int $id
 * @property int $user_id
 * @property string $title
 * @property string $body
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Thread newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Thread newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Thread query()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Thread whereBody($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Thread whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Thread whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Thread whereTitle($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Thread whereUpdatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Thread whereUserId($value)
 * @property-read \App\User $creator
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Reply[] $replies
 */
class Thread extends Model
{
    use RecordsActivity;

    protected $with = ['creator', 'channel'];

    protected $appends = ['isSubscribeTo'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

/*        static::addGlobalScope(function ($builder) {
            return $builder->withCount('replies');
        });*/

        static::deleting(function ($thread) {
            $thread->replies->each->delete();
        });
    }

    protected $guarded = [];

    public function path()
    {
        return "/threads/{$this->channel->slug}/{$this->id}";
    }

    public function replies()
    {
        return $this->hasMany(Reply::class);//->orderBy('created_at');
    }

    public function creator()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function channel()
    {
        return $this->belongsTo(Channel::class);
    }

    public function addReply(array $replyData)
    {
        /** @var Reply $reply */
        $reply = $this->replies()->create($replyData);

        $this->subscriptions
            ->filter(function ($subscription) use ($reply) {
               return  $subscription->user_id != $reply->user_id;
            })
            ->each->notify($reply);

        return $reply;
    }

    public function scopeFilter($query, $filters)
    {
        return $filters->apply($query);
    }

    public function subscribe($userId = null)
    {
        return $this->subscriptions()->create([
            'user_id' => $userId ?: auth()->id(),
        ]);
    }

    public function unsubscribe($userId = null)
    {
        return $this->subscriptions()->where(
            'user_id', $userId ?: auth()->id()
        )->delete();
    }

    public function subscriptions()
    {
        return $this->hasMany(ThreadSubscription::class);
    }

    public function getIsSubscribeToAttribute()
    {
        return $this
            ->subscriptions()
            ->where('user_id', auth()->id())
            ->exists();
    }
}
